name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the assets using Webpack
      run: |
        docker run \
        -v ${{ github.workspace }}:/app -w /app \
        node:16-alpine /bin/ash -c "npm ci && npx encore prod"
    - name: Publish the generated assets to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        target_branch: gh-pages
        keep_history: true
        build_dir: public
        fqdn: leonboot.dev
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}